version: "3.9"

services:

  postgres:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always

volumes:
  data:
